[build.environment]
  HUGO_VERSION = "0.77.0"

[build]
publish = "public"
command = "hugo"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"
