version: 2.1

orbs:
  hugo: circleci/hugo@1.0
  gcp-cli: circleci/gcp-cli@2.1.0

jobs:
  deploy:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - attach_workspace:
          at: my-site
      - run: ls -lah my-site

workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          version: '0.68'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - hugo/build